
image: node:8.12.0

cache:
  paths:
    - node_modules/
    - .npm

stages:
  - build
  - test

build:
 stage: build
 script:
  - sudo npm i

test_unit:
  stage: test
  services:
    - mongo:3.1.6
  script:
  - npm i npm@latest -g
  - npm i
  - DATABASE_URL=mongodb://ec2-34-255-190-53.eu-west-1.compute.amazonaws.com:27017/cookingDB
  - npm run test:unit

test_feature:
  stage: test
  services:
    - mongo:3.1.6
  script:
  - npm i npm@latest -g
  - npm i
  - DATABASE_URL=mongodb://ec2-34-255-190-53.eu-west-1.compute.amazonaws.com:27017/cookingDB
  - npm run test

test_ui:
  stage: test
  services:
    - mongo:3.1.6
  script:
  - npm i npm@latest -g
  - npm i
  - DATABASE_URL=mongodb://ec2-34-255-190-53.eu-west-1.compute.amazonaws.com:27017/cookingDB
  - npm run test:ui


