
image: node:8.12.0

cache:
  paths:
    - node_modules/
    - .npm

stages:
  - build
  - test

build:
 stage: build
 only:
    refs:
      - branches
 script:
  - sudo apt-get update -y
  - sudo apt-get install -y git
  - sudo apt-get install -y curl
  - sudo apt-get install -y nodejs
  - sudo apt-get install -y npm
  - sudo mkdir -p /app
  - cd /app
  - sudo git clone https://github.com/luciagore/cooking.git
  - cd cooking
  - sudo npm install
  - sudo mkdir -p /data/db
  - sudo chmod -R go+w /data/db
  - sudo service mongodb start

test_unit:
  stage: test
  only:
    refs:
      - branches
  services:
    - mongo:3.1.6
  script:
  - npm i npm@latest -g
  - npm i
  - npm run test:unit

test_feature:
  stage: test
  only:
    refs:
      - branches
  services:
    - mongo:3.1.6
  script:
  - npm i npm@latest -g
  - npm i
  - npm run test

test_ui:
  stage: test
  only:
    refs:
      - branches
  services:
    - mongo:3.1.6
  script:
  - npm i npm@latest -g
  - npm i
  - npm run test:ui


