
image: selenium/hub

# cache:
#   paths:
#     - node_modules/
#     - .npm

stages:
  - build
  - test
  - code quality

build:
 stage: build
 script:
  - npm i npm@latest -g
  - npm i

test_unit:
  stage: test
  services:
    - mongo:3.1.6
  script:
  - npm i npm@latest -g
  - npm i
  - DATABASE_URL=mongodb://ec2-34-255-190-53.eu-west-1.compute.amazonaws.com:27017/cookingDB
  - npm run test:unit

test_feature:
  stage: test
  services:
    - mongo:3.1.6
  script:
  - npm i npm@latest -g
  - npm i
  - DATABASE_URL=mongodb://ec2-34-255-190-53.eu-west-1.compute.amazonaws.com:27017/cookingDB
  - npm run test

test_ui:
  stage: test
  image: openjdk:latest
  services:
    - mongo:3.1.6
    - selenium/standalone-chrome:latest
  script:
  - npm i npm@latest -g
  - npm i
  - DATABASE_URL=mongodb://ec2-34-255-190-53.eu-west-1.compute.amazonaws.com:27017/cookingDB
  - npm run test:ui

code_quality:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/codequality:$SP_VERSION" /code
  artifacts:
    reports:
      codequality: [gl-code-quality-report.json]
